// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYP8Av5p0keEpGE2UI14gzwVruavVL5s',
    appId: '1:208558868199:web:f4dfafa5c5bde4c27e0442',
    messagingSenderId: '208558868199',
    projectId: 'ject-af82c',
    authDomain: 'ject-af82c.firebaseapp.com',
    storageBucket: 'ject-af82c.firebasestorage.app',
    measurementId: 'G-JPFDB8BDYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBVjF_vz_z74_SMGFKG8G21HbjW-PUI10',
    appId: '1:208558868199:android:705eb120fdbad1b07e0442',
    messagingSenderId: '208558868199',
    projectId: 'ject-af82c',
    storageBucket: 'ject-af82c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA6Yy6PQnrgDO2SCVVKG_nAZ8q2gU0A6I',
    appId: '1:208558868199:ios:7210a87eb3191c9b7e0442',
    messagingSenderId: '208558868199',
    projectId: 'ject-af82c',
    storageBucket: 'ject-af82c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA6Yy6PQnrgDO2SCVVKG_nAZ8q2gU0A6I',
    appId: '1:208558868199:ios:7210a87eb3191c9b7e0442',
    messagingSenderId: '208558868199',
    projectId: 'ject-af82c',
    storageBucket: 'ject-af82c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCYP8Av5p0keEpGE2UI14gzwVruavVL5s',
    appId: '1:208558868199:web:735a1c216b70f2507e0442',
    messagingSenderId: '208558868199',
    projectId: 'ject-af82c',
    authDomain: 'ject-af82c.firebaseapp.com',
    storageBucket: 'ject-af82c.firebasestorage.app',
    measurementId: 'G-BNPR7ZMTE3',
  );
}
